name: Debug Workflow to run anything on all push events

on:
  push:

jobs:
  debug:
    runs-on: ubuntu-20.04
    steps:
      - name: Print github Context
        env:
          MY_BOOLEAN: ${{ !contains(github.event.commits.*.message, '#skip')}}
        run: |
          echo $MY_BOOLEAN
