name: Debug Workflow to run anything on all push events

on:
  push:

jobs:
  debug:
    runs-on: ubuntu-20.04
    steps:
      - name: Print github Context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: |
          echo $GITHUB_CONTEXT
      - name: Print commit messages
        env:
          COMMITS: ${{ toJSON(github.commits }}
          COMMIT_MESSAGE: ${{ toJSON(github.commits.*.message)}}
          COMMIT_MESSAGE1: ${{ toJSON(github.commits[0].message)}}
        run: |
          echo $COMMITS; echo $COMMIT_MESSAGE; echo $COMMIT_MESSAGE1;
