name: Debug Workflow to run anything on all push events

on:
  push:
    branches:
      - debug

jobs:
  debug:
    runs-on: ubuntu-20.04
    steps:
      - name: Print github Context
        # putting #check in the commit message should echo false
        env:
          COMMIT_MESSAGE: ${{ toJSON(github.event.commits[0].message) }}
          MY_BOOLEAN: ${{ contains(github.event.commits[0].message, '#check')}}
          MY_BOOLEAN_WITH_NOT: ${{ !contains(github.event.commits[0].message, '#check')}}
        run: |
          echo $MY_BOOLEAN; echo $MY_BOOLEAN_WITH_NOT; echo $COMMIT_MESSAGE;
