name: Deployment pipeline

on:
  pull_request:
    branches:
      - master
    types: [opened, reopened, closed]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Install node (npm) dependencies
        run: npm install
      - name: Lint
        run: npm run eslint
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
      - name: e2e tests
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000
      - name: deploy
        if: ${{ github.event_name == 'push' && !contains(github.event.commits[0].message, '#skip') }}
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: 'pokedox-fsopen' #Must be unique in Heroku
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          healthcheck: https://pokedox-fsopen.herokuapp.com/healthcheck
          checkstring: ok
          rollbackonhealthcheckfailed: true
